service: wallet

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  stage: ${opt:stage, 'dev'}
  timeout: 30
  memorySize: 1024
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  lambdaWallet:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agen
              - x-access-token

  updateInvestments:
    handler: src/presentation/propagateActions/PropagateActions.handler
    events:
      - schedule:
          rate: rate(6 hours)
      - http:
          path: /propagateAction
          method: GET
          cors: true


resources:
  Resources:
    userTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: 'WalletUser'
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


