service:
  name: wallet-backend
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello-world:
    handler: src/presentation/hello/_routes.handler
    events:
      - http:
          path: hello/{proxy+}
          method: any
          cors: true

